### ISSUE TITLE
Newly added calendar event is not visible in web frontend

### ISSUE THREAD

**Issue by nebulade** [inverse-inc/sogo#192]
Hi,

from the issue reported on the mailing list. Relevant for v3 only. Events added through the webinterface, which does not have any repeat set, are not visible in the calendar view, until such an event is 'touched' and saved unchanged in for example Thunderbird. From that point on it will be visible normally in the webui.

After adding such an event, the GET requests to eventblocks simply would not contain the new event, after the event is added in some externally synchronized calendar app.

This happens on both current Chrome, as well as Firefox. Also from the mailing list, it also appears to happen with using nginx reverse proxy or an apache setup (reported by @andryyy )

Thanks

**Comment by cgx** [comment]
Which calendar view are you using (day/week/month)? Which day/week/month is selected? Are you trying to create an event in your personal calendar? Is your personal calendar enabled?

**Comment by nebulade** [comment]
Yes in my personal calendar, and it is enabled. I have tried now all combinations of the view, also in various months throughout this and last year. Note that the POST request to create the event is just fine, only the event list request (GET eventblocks) would return an `events` array without the newly created event, for any view which should contain it. After I touch that same event and sync with thunderbird, the event is part of the result for the very same views failing earlier.

Forgot to add the server log during the even creation here (copy from the mailing list):
```
Jan 28 12:58:30 sogod [24]: [ERROR] <0x0x7eff615b18a0[iCalRecurrenceCalculator]> unsupported rrule frequency: <0x5610b2b89210[iCalRecurrenceRule]:rrule
```

**Comment by cgx** [comment]
If you visit your user's preferences, is the timezone set?

**Comment by andryyy** [comment]
Yes, mine was set to Berlin, switched to NY for testing, but nothing changed.

**Comment by nebulade** [comment]
It is set to UTC, now I have changed it to Berlin, still the same.
The event is correct in my synchronized Thunderbird calendar.

**Comment by andryyy** [comment]
Maybe it helps, the request payload:
```
{
	"categories": [],
	"repeat": {
		"frequency": "never"
	},
	"alarm": {},
	"status": "not-specified",
	"delta": 60,
	"pid": "personal",
	"type": "appointment",
	"start": "2016-01-29T20:45:32.942Z",
	"end": "2016-01-29T21:45:32.942Z",
	"destinationCalendar": "personal",
	"freebusy": {
		"20160129": {
			"21": [0, 0, 0, 1],
			"22": [1, 1, 1]
		}
	},
	"selected": false,
	"isNew": true,
	"classification": "public",
	"id": "E0E-56ABD000-5-584C5480.ics",
	"location": "test",
	"comment": "test",
	"summary": "asddsa",
	"startDate": "2016-01-29",
	"startTime": "21:45",
	"endDate": "2016-01-29",
	"endTime": "22:45",
	"dueDate": "",
	"dueTime": ""
}
```

**Comment by andryyy** [comment]
New information:
@nebulade I think your "unsupported rrule frequency" is due to setting the timezone to "UTC", because there is no ics file in prefix/Libraries/Resources/NGCards/TimeZones for it. I don't see this error with Europe/Berlin being set.

I created an event in the web UI and read the db:
```
PRODID:-//Inverse inc./SOGo 3.0.0//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:243C-56ACA200-1-6E3B5080
SUMMARY:1465
LOCATION:45234
CLASS:PUBLIC
STATUS:NOT-SPECIFIED
DTSTART;TZID=Europe/Berlin:20160130T124500
DTEND;TZID=Europe/Berlin:20160130T134500
CREATED:20160130T114409Z
DTSTAMP:20160130T114409Z
LAST-MODIFIED:20160130T114409Z
END:VEVENT
END:VCALENDAR |     1454154249 |     1454154249 |         0 |      NULL |
```
Then I touched it with Thunderbird an re-read the item:
```
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20160130T114409Z
LAST-MODIFIED:20160130T114834Z
DTSTAMP:20160130T114834Z
UID:243C-56ACA200-1-6E3B5080
SUMMARY:1465
DTSTART;TZID=Europe/Berlin:20160130T124500
DTEND;TZID=Europe/Berlin:20160130T134500
LOCATION:45234
CLASS:PUBLIC
X-MOZ-GENERATION:1
END:VEVENT
END:VCALENDAR |     1454154249 |     1454154504 |         1 |      NULL |
```
Maybe it helps.

**Comment by andryyy** [comment]
Okay, I was looking in the wrong table, but I found the error:
SOGo inserts `c_iscycle=1` to `sogoandremai00147b4991d_quick` though it should be `c_iscycle=0`. Touching the record with Thunderbird sets `c_iscycle=0`. It also appears in the UI when I update the table by hand.

**Comment by andryyy** [comment]
Looks like it was fixed with 687521d

**Comment by tdragonite** [comment]
I don't think that commit fix this problem.
I've tried to manually apply it but the problem is still present :-P

**Comment by cgx** [comment]
@tdragonite Applying the patch is not enough. Did you regenerate the JavaScript?

**Comment by tdragonite** [comment]
@cgx .. ahem, u're right. Totally forgotten :-P sorry, I'll try asap

**Comment by hinoyouni** [comment]
@tdragonite, could you please tell me how to regenerate the JavaScript ? Thanks

**Comment by cgx** [comment]
Should be fixed with bd4f42b9483e849a5b8a1a9b9bd403184ec73204
